### ISSUE TITLE
UnsupportedClassVersionError: incanter/Matrix : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by DuckOfDoom** [incanter/incanter#332]
Getting this error in REPL:

```
matrices.core=> (use '(incanter core stats charts io))

CompilerException java.lang.UnsupportedClassVersionError: incanter/Matrix : Unsupported major.minor version 52.0, compiling:(incanter/core.clj:2277:1)
```

Here are my project.clj :dependencies :
```
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [net.mikera/core.matrix "0.50.1"]
                 [clatrix "0.5.0"]
                 [incanter "1.5.7"]]
```

Any workaround for this?

**Comment by DuckOfDoom** [comment]
Guess Incanter doesn't work with Clojure > 1.6.0...

**Comment by davisn** [comment]
Actually, I get the same error with Clojure 1.6.0 ... so I don't think that's the problem.

**Comment by DuckOfDoom** [comment]
@davisn For me it worked with the same configuration as in tutorial:

`:dependencies [[org.clojure/clojure "1.6.0"]  [incanter "1.5.7"]]`

**Comment by davisn** [comment]
@DuckOfDoom, well it doesn't work for me -- straight from the tutorial or not.

I think the problem is that the Matrix class was compiled targeting Java 1.8 and so it [doesn't work with JDK 1.7](http://stackoverflow.com/questions/23249331/java-unsupported-major-minor-version-52-0) (which is what I'm running).  Cloning the repository and installing `incanter.core` via `lein install` (with JDK 1.7) appears to fix the issue for me.

It would probably be a good idea to specify a target Java version when compiling `.java` files.  I believe this can be accomplished by adding the following to `incanter.core`'s `project.clj` (changing the version to whatever you feel is appropriate -- probably the minimum version of Java supported by the minimum version of Clojure incanter is supposed to support):

   :javac-options     ["-target" "1.7"]

See [Setting Java Compiler Options with Leiningen](https://github.com/technomancy/leiningen/blob/master/doc/MIXED_PROJECTS.md#setting-java-compiler-options-with-leiningen) section of [Polyglot (Clojure, Java) Projects With Leiningen](https://github.com/technomancy/leiningen/blob/master/doc/MIXED_PROJECTS.md) for more details.

**Comment by metasoarous** [comment]
Would be nice to see some sort of fix for this.
